baseurl = "https://joaoarthurbm.github.io/dev-ia"
title = "Desenvolvimento de Software com Agentes e IA Generativa"
copyright = "Copyright &copy; 2026 - joaoarthurbm.github.io. Licença de uso: versão para uso pessoal, sendo proibida sua redistribuição ou modificação."
canonifyurls = true
theme = "kiera"
themesDir = "themes"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "João Arthur Brunet"
    github = "https://github.com/joaoarthurbm/dev-ia"
    gitlab = ""
    linkedin = ""
    facebook = ""
    lattes = "7892247821251194"

[params]
    tagline = "[joaoarthurbm.github.io](https://joaoarthurbm.github.io) <br> Computação @ UFCG"

    [params.Assets]
        customCSS = ["css/site.css"]

[[menu.main]]
    name = "Home"
    url = "/"
    identifier = "home"
    weight = -100
    pre = "fa-home"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true